apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yqp52z540-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yqp52z540-go 
  name: yqp52z540-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yqp52z540-go 
