apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yqp52z540-go 
  janus-idp.io/tekton: yqp52z540-go
  backstage.io/kubernetes-id: yqp52z540-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yqp52z540-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  